# Site settings
title: Lyon Ling's Blog
SEOTitle: LYON的博客 | LYON's Blog
header-img: img/post-bg-2015.jpg
email: leonling@ust.hk
description: "孤独是人生的常态吗？"
keyword: "lyonling, 凌丽阳, LYON's Blog "
url: "http://lyonling.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lyonling/lyonling.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "There is no easy word, but insisting always worthes."
sidebar-avatar: /img/avatar_5.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     5395966937
zhihu_username:     lyonling
github_username:    lyonling
facebook_username:  lyon.ling.737
jianshu_username:   751e67c131d6
linkedin_username:  liyang-ling-678220117
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge
  math_engine: MathJax


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true


# 评论系统
# Disqus（https://disqus.com/）
# disqus:
#   enable: true
#   username: leon_disqus
disqus_username: leon_disqus

# Duoshuo settings
# duoshuo_username: username
# duoshuo_share: true   

# Netease settings
netease_comment: false

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 2c2d5b074f967ff240c0                            #生成的clientID
  clientSecret: 96f1e9daf40336e5d1597723a42c8c130d4b3887    #生成的clientSecret
  repo: lyonling.github.io    #仓库名称
  owner: lyonling    #github用户名
  admin: lyonling
  distractionFreeMode: false #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-131740306-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Max Qi",
        href: "http://cherishher.github.io/"
    },{
        title: "Gu Chenghao",
        href: "http://http://www.guchenghao.com/"
    },{
        title: "Syen Park",
        href: "https://syenpark.github.io/"
    }
]
