# Site settings
title: Leon Ling's Blog
SEOTitle: LEON的博客 | LEON's Blog
header-img: img/home-bg-1.jpg
email: leonling@ust.hk
description: "人的一生总是为了追寻生命中的光，而走在漫长的路上"
keyword: "leonling, 凌丽阳, LEON's Blog "
url: "http://liyanglingintel.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/liyanglingintel/liyanglingintel.github.io" # you code repository
                           # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     5395966937
zhihu_username:     lyonling
github_username:    liyanglingintel
# facebook_username:  lyon.ling.737
# jianshu_username:   751e67c131d6
linkedin_username:  liyang-ling-678220117


# Footer start year
start_year: 2018


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# 评论系统
# Disqus（https://disqus.com/）
disqus:
  enable: false
  username: leon_disqus

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: d7fba9493986b68b449e                            #生成的clientID
  clientSecret: 7fda770b11cf099b440e62b0b1116cb47cb8c4e4    #生成的clientSecret
  repo: LiyangLingIntel.github.io    #仓库名称
  owner: LiyangLingIntel    #github用户名
  admin: [LiyangLingIntel,]
  distractionFreeMode: false #是否启用类似FB的阴影遮罩


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-131740306-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里自定义了的域名，需要改成域名



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "秋风吹渭水, 叶落满长安"
sidebar-avatar: /img/avatar_8.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 4              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



## => On Site Search
##############################
search:
  enable: true



## => Sources
##############################
sources: bootcdn # bootcdn (default), unpkg



# Friends
friends: [
    {
        title: "Max Qi",
        href: "https://cherishher.github.io/"
    },{
        title: "Gu Chenghao",
        href: "https://www.guchenghao.com/"
    },{
        title: "Syen Park",
        href: "https://syenpark.github.io/"
    },{
        title: "DOJO Zheng",
        href: "https://dojozheng.com/"
    },{
        title: "Richard YU",
        href: "https://richardyu114.github.io/"
    },{
        title: "Ruolan",
        href: "https://junewangrl.github.io/"
    }
]
